//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notDefteri.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class notTablosu
    {
        public int id { get; set; }
        public string notAdi { get; set; }
        public string notTarih { get; set; }
        public string not { get; set; }
        public string mesajin { get; set; }
    }
}
